import pandas as pd

# Define the starter HVAC pricebook (≈60 items)
items = [
    # --- Maintenance ---
    dict(SKU="AC-TU-01", Category="Maintenance > Tune-Up", Task_Name="Full A/C Tune‑Up (1 System)",
         Tech_Notes="Check ΔT, clean outdoor coil, flush drain, tighten lugs", Customer_Description="Seasonal tune‑up & 21‑point inspection",
         Standard_Price=185, Membership_Price=135, After_Hours_Price=250, Est_Hours=1.0, Equipment_Type="Air Conditioner",
         Parts_Kit="", Warranty_Code=""),
    dict(SKU="HT-TU-01", Category="Maintenance > Tune-Up", Task_Name="Gas Furnace Tune‑Up",
         Tech_Notes="Clean burners, check flame sensor, inspect HX", Customer_Description="Annual furnace tune‑up & safety check",
         Standard_Price=165, Membership_Price=120, After_Hours_Price=225, Est_Hours=1.0, Equipment_Type="Furnace",
         Parts_Kit="", Warranty_Code=""),
    dict(SKU="HP-TU-01", Category="Maintenance > Tune-Up", Task_Name="Heat Pump Tune‑Up",
         Tech_Notes="Defrost board test, coil wash, refrigerant check", Customer_Description="Comprehensive heat‑pump tune‑up",
         Standard_Price=195, Membership_Price=145, After_Hours_Price=260, Est_Hours=1.2, Equipment_Type="Heat Pump",
         Parts_Kit="", Warranty_Code=""),
    dict(SKU="IAQ-FLT-01", Category="Maintenance > Filter", Task_Name="Replace Standard 1\" Filter (pair)",
         Tech_Notes="Verify airflow direction", Customer_Description="Change disposable 1\" filters",
         Standard_Price=35, Membership_Price=25, After_Hours_Price=50, Est_Hours=0.2, Equipment_Type="Air Conditioner",
         Parts_Kit="1\" Filter (2)", Warranty_Code=""),
    dict(SKU="IAQ-FLT-02", Category="Maintenance > Filter", Task_Name="Replace 4\" Media Filter",
         Tech_Notes="Check static pressure post-change", Customer_Description="Media filter replacement",
         Standard_Price=90, Membership_Price=70, After_Hours_Price=120, Est_Hours=0.3, Equipment_Type="Air Conditioner",
         Parts_Kit="4\" Media Filter", Warranty_Code=""),
    dict(SKU="MAI-COIL-CL", Category="Maintenance > Cleaning", Task_Name="Outdoor Coil Deep‑Clean",
         Tech_Notes="Chemical foaming coil cleaner, low‑pressure rinse", Customer_Description="Deep clean outdoor condenser coil",
         Standard_Price=185, Membership_Price=145, After_Hours_Price=245, Est_Hours=1.0, Equipment_Type="Air Conditioner",
         Parts_Kit="Foam cleaner", Warranty_Code=""),
    dict(SKU="MAI-BLOW-CL", Category="Maintenance > Cleaning", Task_Name="Blower Wheel Cleaning",
         Tech_Notes="Remove wheel, degrease, balance check", Customer_Description="Blower wheel cleaning service",
         Standard_Price=225, Membership_Price=175, After_Hours_Price=295, Est_Hours=1.3, Equipment_Type="Air Handler",
         Parts_Kit="", Warranty_Code=""),
    dict(SKU="MAI-DUC-CL", Category="Maintenance > Cleaning", Task_Name="Duct Sanitizing (up to 10 vents)",
         Tech_Notes="Fog EPA-listed sanitizer", Customer_Description="Whole‑home duct sanitizing treatment",
         Standard_Price=350, Membership_Price=280, After_Hours_Price=450, Est_Hours=1.5, Equipment_Type="Ductwork",
         Parts_Kit="Sanitizer", Warranty_Code=""),
    dict(SKU="MAI-DRAIN-CLR", Category="Maintenance > Cleaning", Task_Name="Condensate Drain Flush",
         Tech_Notes="Vacuum & flush with condensate tablets", Customer_Description="Clear & treat AC drain line",
         Standard_Price=120, Membership_Price=90, After_Hours_Price=160, Est_Hours=0.6, Equipment_Type="Air Conditioner",
         Parts_Kit="Drain tabs", Warranty_Code=""),
    dict(SKU="MAI-INSP-01", Category="Maintenance > Inspection", Task_Name="Comprehensive System Inspection",
         Tech_Notes="Document 30‑point checklist in app", Customer_Description="Full HVAC inspection report",
         Standard_Price=140, Membership_Price=105, After_Hours_Price=190, Est_Hours=1.0, Equipment_Type="HVAC System",
         Parts_Kit="", Warranty_Code=""),

    # --- Diagnostics ---
    dict(SKU="DIAG-AC", Category="Diagnostic", Task_Name="A/C System Diagnostic (No Cool)",
         Tech_Notes="Pressure check, electrical diagnostics", Customer_Description="Diagnostic visit – air conditioner not cooling",
         Standard_Price=99, Membership_Price=75, After_Hours_Price=149, Est_Hours=0.8, Equipment_Type="Air Conditioner",
         Parts_Kit="", Warranty_Code=""),
    dict(SKU="DIAG-FUR", Category="Diagnostic", Task_Name="Furnace Diagnostic (No Heat)",
         Tech_Notes="Ignition sequence test, gas pressure", Customer_Description="Diagnostic visit – furnace not heating",
         Standard_Price=99, Membership_Price=75, After_Hours_Price=149, Est_Hours=0.8, Equipment_Type="Furnace",
         Parts_Kit="", Warranty_Code=""),
    dict(SKU="DIAG-HP", Category="Diagnostic", Task_Name="Heat Pump Diagnostic",
         Tech_Notes="Check reversing valve, defrost cycle", Customer_Description="Diagnostic visit – heat pump issue",
         Standard_Price=109, Membership_Price=85, After_Hours_Price=159, Est_Hours=0.9, Equipment_Type="Heat Pump",
         Parts_Kit="", Warranty_Code=""),
    dict(SKU="DIAG-IAQ", Category="Diagnostic", Task_Name="Indoor Air Quality Assessment",
         Tech_Notes="CO, humidity, particulate reading", Customer_Description="Whole‑home IAQ evaluation",
         Standard_Price=80, Membership_Price=60, After_Hours_Price=120, Est_Hours=0.7, Equipment_Type="HVAC System",
         Parts_Kit="", Warranty_Code=""),
    dict(SKU="DIAG-ELC", Category="Diagnostic", Task_Name="Electrical Fault Diagnostic",
         Tech_Notes="Megohm test motors, inspect wiring", Customer_Description="Electrical troubleshooting visit",
         Standard_Price=120, Membership_Price=95, After_Hours_Price=170, Est_Hours=1.0, Equipment_Type="HVAC System",
         Parts_Kit="", Warranty_Code=""),

    # --- Repairs ---
    dict(SKU="AC-CAP-45", Category="Repair > Electrical", Task_Name="Replace Capacitor 45/5 µF",
         Tech_Notes="Verify microfarads ±6%", Customer_Description="Capacitor replacement",
         Standard_Price=220, Membership_Price=175, After_Hours_Price=310, Est_Hours=0.6, Equipment_Type="Air Conditioner",
         Parts_Kit="45/5 Cap", Warranty_Code=""),
    dict(SKU="AC-CNT-40", Category="Repair > Electrical", Task_Name="Replace Contactor 40 A",
         Tech_Notes="Check coil voltage and line lugs", Customer_Description="Contactor replacement",
         Standard_Price=240, Membership_Price=190, After_Hours_Price=330, Est_Hours=0.7, Equipment_Type="Air Conditioner",
         Parts_Kit="40A Contactor", Warranty_Code=""),
    dict(SKU="AC-MTR-COND", Category="Repair > Mechanical", Task_Name="Condenser Fan‑Motor Replacement",
         Tech_Notes="Replace fan blades if bent", Customer_Description="Condenser fan motor replacement",
         Standard_Price=540, Membership_Price=450, After_Hours_Price=690, Est_Hours=1.5, Equipment_Type="Air Conditioner",
         Parts_Kit="Motor, capacitor", Warranty_Code=""),
    dict(SKU="AC-COMP-RPL", Category="Repair > Mechanical", Task_Name="Compressor Replacement (3‑ton, R‑410A)",
         Tech_Notes="Weigh in R‑410A charge to spec", Customer_Description="Air‑conditioner compressor replacement",
         Standard_Price=2450, Membership_Price=2150, After_Hours_Price=3150, Est_Hours=4.0, Equipment_Type="Air Conditioner",
         Parts_Kit="Compressor, drier", Warranty_Code="COMP-10YR"),
    dict(SKU="AC-COIL-EVAP", Category="Repair > Mechanical", Task_Name="Evaporator Coil Replacement",
         Tech_Notes="Install TXV, pressure test 300 psi", Customer_Description="Evaporator coil replacement",
         Standard_Price=1550, Membership_Price=1350, After_Hours_Price=2050, Est_Hours=3.0, Equipment_Type="Air Conditioner",
         Parts_Kit="Coil, TXV", Warranty_Code=""),
    dict(SKU="FUR-IGN", Category="Repair > Electrical", Task_Name="Hot‑Surface Igniter Replacement",
         Tech_Notes="Verify 120 V to igniter", Customer_Description="Igniter replacement",
         Standard_Price=285, Membership_Price=230, After_Hours_Price=390, Est_Hours=0.8, Equipment_Type="Furnace",
         Parts_Kit="HSI", Warranty_Code=""),
    dict(SKU="FUR-HX", Category="Repair > Mechanical", Task_Name="Heat Exchanger Replacement (Gas Furnace)",
         Tech_Notes="Combustion test post‑install", Customer_Description="Heat exchanger replacement",
         Standard_Price=1350, Membership_Price=1150, After_Hours_Price=1850, Est_Hours=3.5, Equipment_Type="Furnace",
         Parts_Kit="HX kit", Warranty_Code="HX-20YR"),
    dict(SKU="HP-REV-VAL", Category="Repair > Refrigerant", Task_Name="Reversing Valve Replacement",
         Tech_Notes="Brazing with nitrogen purge", Customer_Description="Heat‑pump reversing valve replacement",
         Standard_Price=1600, Membership_Price=1400, After_Hours_Price=2100, Est_Hours=3.5, Equipment_Type="Heat Pump",
         Parts_Kit="Rev valve, drier", Warranty_Code=""),
    dict(SKU="AC-TXV-RPL", Category="Repair > Refrigerant", Task_Name="TXV Replacement",
         Tech_Notes="Adjust superheat post‑install", Customer_Description="Thermostatic expansion valve replacement",
         Standard_Price=780, Membership_Price=640, After_Hours_Price=1010, Est_Hours=2.0, Equipment_Type="Air Conditioner",
         Parts_Kit="TXV, drier", Warranty_Code=""),
    dict(SKU="AC-LEAK-FIX", Category="Repair > Refrigerant", Task_Name="Refrigerant Leak Search & Repair",
         Tech_Notes="Electronic & bubbles test, braze leaks", Customer_Description="Leak search and repair",
         Standard_Price=620, Membership_Price=500, After_Hours_Price=820, Est_Hours=2.5, Equipment_Type="Air Conditioner",
         Parts_Kit="N2, brazing rods", Warranty_Code=""),
    dict(SKU="AC-REFCHG-R410A", Category="Repair > Refrigerant", Task_Name="Recharge R‑410A (per lb)",
         Tech_Notes="Weigh in to factory spec", Customer_Description="Refrigerant recharge per pound",
         Standard_Price=90, Membership_Price=75, After_Hours_Price=120, Est_Hours=0.2, Equipment_Type="Air Conditioner",
         Parts_Kit="R‑410A", Warranty_Code=""),
    dict(SKU="AC-BLW-MTR", Category="Repair > Mechanical", Task_Name="Blower Motor Replacement (PSC)",
         Tech_Notes="Set correct speed tap", Customer_Description="Blower motor replacement",
         Standard_Price=520, Membership_Price=430, After_Hours_Price=660, Est_Hours=1.4, Equipment_Type="Air Handler",
         Parts_Kit="Motor, capacitor", Warranty_Code=""),
    dict(SKU="THERM-REPL", Category="Repair > Controls", Task_Name="Thermostat Replacement (Non‑WiFi)",
         Tech_Notes="Calibrate, set programs", Customer_Description="Standard digital thermostat replacement",
         Standard_Price=250, Membership_Price=200, After_Hours_Price=340, Est_Hours=0.7, Equipment_Type="Controls",
         Parts_Kit="Thermostat", Warranty_Code=""),
    dict(SKU="LINE-DRAIN-RPL", Category="Repair > Plumbing", Task_Name="Condensate Pump Replacement",
         Tech_Notes="Prime pump, test float", Customer_Description="Replace condensate pump",
         Standard_Price=310, Membership_Price=250, After_Hours_Price=410, Est_Hours=1.0, Equipment_Type="Air Conditioner",
         Parts_Kit="Pump, tubing", Warranty_Code=""),
    dict(SKU="AC-SURG-PROT", Category="Repair > Electrical", Task_Name="HVAC Surge Protector Install",
         Tech_Notes="Mount in disconnect, 240 V", Customer_Description="Install surge protector on condenser",
         Standard_Price=295, Membership_Price=240, After_Hours_Price=395, Est_Hours=0.9, Equipment_Type="Air Conditioner",
         Parts_Kit="Surge protector", Warranty_Code=""),
    dict(SKU="AC-DEF-RLY", Category="Repair > Electrical", Task_Name="Defrost Control Board Replacement",
         Tech_Notes="Check sensors, test defrost cycle", Customer_Description="Replace defrost board",
         Standard_Price=420, Membership_Price=340, After_Hours_Price=560, Est_Hours=1.3, Equipment_Type="Heat Pump",
         Parts_Kit="Board", Warranty_Code=""),
    dict(SKU="HP-CTRL-BRD", Category="Repair > Electrical", Task_Name="Heat Pump Control Board Replacement",
         Tech_Notes="Program DIP switches", Customer_Description="Replace heat‑pump control board",
         Standard_Price=480, Membership_Price=390, After_Hours_Price=640, Est_Hours=1.4, Equipment_Type="Heat Pump",
         Parts_Kit="Control board", Warranty_Code=""),
    dict(SKU="AC-DRIER-RPL", Category="Repair > Refrigerant", Task_Name="Liquid Line Drier Replacement",
         Tech_Notes="Braze bi‑flow drier, vacuum 500 microns", Customer_Description="Replace refrigerant drier",
         Standard_Price=260, Membership_Price=210, After_Hours_Price=350, Est_Hours=1.0, Equipment_Type="Air Conditioner",
         Parts_Kit="Drier", Warranty_Code=""),
    dict(SKU="AC-GAS-ADJ", Category="Repair > Combustion", Task_Name="Gas Valve Adjustment",
         Tech_Notes="Set manifold pressure per spec", Customer_Description="Adjust furnace gas valve",
         Standard_Price=160, Membership_Price=125, After_Hours_Price=220, Est_Hours=0.6, Equipment_Type="Furnace",
         Parts_Kit="", Warranty_Code=""),
    dict(SKU="AC-COIL-LEAK-TEST", Category="Repair > Refrigerant", Task_Name="Add Leak Stop Additive",
         Tech_Notes="Inject sealant, monitor pressures", Customer_Description="Leak sealant additive service",
         Standard_Price=240, Membership_Price=190, After_Hours_Price=330, Est_Hours=0.8, Equipment_Type="Air Conditioner",
         Parts_Kit="Sealant", Warranty_Code=""),
    # additional repairs to reach 25
    dict(SKU="AC-DUCT-REPAIR", Category="Repair > Airflow", Task_Name="Minor Duct Repair (per joint)",
         Tech_Notes="Mastic seal, tape as needed", Customer_Description="Seal leaking duct joint",
         Standard_Price=140, Membership_Price=110, After_Hours_Price=200, Est_Hours=0.5, Equipment_Type="Ductwork",
         Parts_Kit="Mastic, tape", Warranty_Code=""),
    dict(SKU="AC-DRAIN-PAN", Category="Repair > Plumbing", Task_Name="Secondary Drain Pan Replacement",
         Tech_Notes="Level pan, reinstall float switch", Customer_Description="Replace secondary drain pan",
         Standard_Price=620, Membership_Price=520, After_Hours_Price=820, Est_Hours=2.0, Equipment_Type="Air Handler",
         Parts_Kit="Drain pan", Warranty_Code=""),

    # --- Installations ---
    dict(SKU="IAQ-UV-01", Category="Install > IAQ", Task_Name="Install 24 V UV Light",
         Tech_Notes="Wire to R & C, mount in supply plenum", Customer_Description="Install germicidal UV light",
         Standard_Price=385, Membership_Price=335, After_Hours_Price=485, Est_Hours=1.2, Equipment_Type="Air Handler",
         Parts_Kit="UV kit", Warranty_Code=""),
    dict(SKU="IAQ-STAT-WIFI", Category="Install > Controls", Task_Name="Install Wi‑Fi Thermostat",
         Tech_Notes="Connect Wi‑Fi, educate homeowner", Customer_Description="Wi‑Fi thermostat install & setup",
         Standard_Price=325, Membership_Price=275, After_Hours_Price=425, Est_Hours=1.0, Equipment_Type="Controls",
         Parts_Kit="Wi‑Fi thermostat", Warranty_Code=""),
    dict(SKU="AC-EZ-TRAP", Category="Install > Plumbing", Task_Name="Install EZ‑Trap + Float Switch",
         Tech_Notes="Wire float to Y circuit", Customer_Description="Install condensate safety switch",
         Standard_Price=260, Membership_Price=210, After_Hours_Price=360, Est_Hours=1.0, Equipment_Type="Air Conditioner",
         Parts_Kit="EZ‑Trap, float", Warranty_Code=""),
    dict(SKU="IAQ-SCRUB", Category="Install > IAQ", Task_Name="Install Air Scrubber",
         Tech_Notes="Mount in supply, wire 24 V", Customer_Description="Install active air scrubber device",
         Standard_Price=895, Membership_Price=795, After_Hours_Price=1095, Est_Hours=1.5, Equipment_Type="Air Handler",
         Parts_Kit="Air scrubber", Warranty_Code=""),
    dict(SKU="DUCT-ZONE-01", Category="Install > Airflow", Task_Name="Install Zoning Damper (8\"‑10\")",
         Tech_Notes="Connect to zone panel, test close/open", Customer_Description="Add motorized zoning damper",
         Standard_Price=780, Membership_Price=660, After_Hours_Price=1010, Est_Hours=2.0, Equipment_Type="Ductwork",
         Parts_Kit="Damper, wiring", Warranty_Code=""),
    dict(SKU="DUCT-RET-ADD", Category="Install > Airflow", Task_Name="Add Return Air Duct (≤15 ft)",
         Tech_Notes="Install grille, flex, mastic seal", Customer_Description="Add new return for airflow balance",
         Standard_Price=980, Membership_Price=820, After_Hours_Price=1280, Est_Hours=2.5, Equipment_Type="Ductwork",
         Parts_Kit="Flex duct, grille", Warranty_Code=""),
    dict(SKU="MINI-001", Category="Install > Mini‑Split", Task_Name="Install Single‑Zone Mini‑Split (9–12k BTU)",
         Tech_Notes="Vacuum, flare torque spec", Customer_Description="Mini‑split installation (indoor & outdoor units)",
         Standard_Price=3900, Membership_Price=3500, After_Hours_Price=4500, Est_Hours=6.0, Equipment_Type="Mini‑Split",
         Parts_Kit="Line set, pad, whip", Warranty_Code=""),
    dict(SKU="AC-CWIRE", Category="Install > Controls", Task_Name="Add C‑Wire Adapter",
         Tech_Notes="Install power extender kit", Customer_Description="Add common wire for smart thermostat",
         Standard_Price=200, Membership_Price=160, After_Hours_Price=280, Est_Hours=0.9, Equipment_Type="Controls",
         Parts_Kit="C‑wire kit", Warranty_Code=""),
    dict(SKU="IAQ-HUM-ADD", Category="Install > IAQ", Task_Name="Install Whole‑House Humidifier",
         Tech_Notes="Mount bypass humidifier, set humidistat", Customer_Description="Whole‑home humidifier installation",
         Standard_Price=950, Membership_Price=800, After_Hours_Price=1250, Est_Hours=3.0, Equipment_Type="Air Handler",
         Parts_Kit="Humidifier kit", Warranty_Code=""),
    dict(SKU="IAQ-DEHUM-ADD", Category="Install > IAQ", Task_Name="Install Whole‑House Dehumidifier",
         Tech_Notes="Duct into return, separate drain", Customer_Description="Whole‑home dehumidifier installation",
         Standard_Price=2900, Membership_Price=2500, After_Hours_Price=3500, Est_Hours=5.0, Equipment_Type="Air Handler",
         Parts_Kit="Dehumidifier, flex", Warranty_Code="")
]

# Create DataFrame
df = pd.DataFrame(items)

# Save to CSV
file_path = "/mnt/data/hvac_pricebook.csv"
df.to_csv(file_path, index=False)

file_path
